export const GET_CURRENT_LOC_WEATHER_DATA = 'GET_CURRENT_LOC_WEATHER_DATA';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_CURRENT_LOC_WEATHER_DATA = 'SET_CURRENT_LOC_WEATHER_DATA';
export const SET_CURRENT_LOC_FORCAST_WEATHER_DATA = 'SET_CURRENT_LOC_FORCAST_WEATHER_DATA';
export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_IN_ERROR = "SIGN_IN_ERROR"